baseURL = "https://zhaolion.com"
languageCode = "zh-CN"
title = "zhaolion's dropbox"
theme = "lion"
publishDir = "dist/public"
ignoreFiles = ["README.md$"]

## 保持分类的原始名字（false会做转小写处理）
preserveTaxonomyNames = true

## 是否禁止URL Path转小写
disablePathToLower = true

## GA
googleAnalytics = "UA-132382167-1"

[author]
    name = "zhaolion"

[[menu.main]]
      name = "归档"
      weight = 20
      identifier = "archives"
      url = "/archives/"

[params]
    author = "zhaolion"
    subtitle = "[翻墙食用]和大家一起分享我们都不知道的东西"
    keywords = "萌新"
    description = "写代码 5 分钟，摸鱼 2 小时"
    busuanzi = true

[params.utteranc]
    enable = true
    repo = "zhaolion/chaldea-comments"    # 存储评论的Repo，格式为 owner/repo
    issueTerm = "pathname"  #表示你选择以那种方式让github issue的评论和你的文章关联。
    theme = "github-light" # 样式主题，有github-light和github-dark两种

[[params.links]]
  title = "Github"
  name = "欢迎来围观我的同性交友账号"
  url = "https://github.com/zhaolion"
