#!/bin/bash

echo -e "\033[0;32mDeploying updates to GitHub...\033[0m"

# Build the project.
hugo # if using a theme, replace with `hugo -t <YOURTHEME>`

## Go to post path
cd content/post
# Add changes to git.
git add .
# Commit changes.
post_msg="daily update `date`"
git commit -m "$post_msg"
# Push source and post repos.
git push origin master

# Come Back up to the Project Root
cd ../..

# Go To Public folder
cd dist/public
# Add changes to git.
git add .
# Commit changes.
msg="rebuilding site `date`"
git commit -m "$msg"
# Push source and build repos.
git push origin master

# Come Back up to the Project Root
cd ../..

echo -e "\033[0;32m又更新博客了，你真棒!\033[0m"